### ISSUE TITLE
Crash with MineLP 1.19.3+LTS

### ISSUE THREAD

**Issue by coppercore** [Sollace/Unicopia#110]
Was testing with MineLP 4.8.6+lts.1.19.3 and Unicopia 1.0.0, looks like Unicopia is calling a function in MineLP when trying to render the player model in 3rd person?

The crash happens in singleplayer when i press F5. All I did was clear out my MineLP skin in HDSkins, reupload the main and then the saddlebag texture and boom.
```
You should try our sister game, Minceraft!
Time: 2023-04-11 09:37:57
Description: Rendering entity in world
java.lang.NoSuchMethodError: 'void com.minelittlepony.api.model.IPart.setRotationAndAngles(boolean, java.util.UUID, float, float, float, float)'
	at com.minelittlepony.unicopia.client.minelittlepony.WingsGear.pose(WingsGear.java:73)
	at com.minelittlepony.client.render.entity.feature.GearFeature.renderGear(GearFeature.java:87)
	at com.minelittlepony.client.render.entity.feature.GearFeature.render(GearFeature.java:80)
	at com.minelittlepony.client.render.entity.feature.GearFeature.method_4199(GearFeature.java:26)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.method_4215(PlayerPonyRenderer.java:77)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.method_3936(PlayerPonyRenderer.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.minelittlepony.unicopia.client.minelittlepony.WingsGear.pose(WingsGear.java:73)
	at com.minelittlepony.client.render.entity.feature.GearFeature.renderGear(GearFeature.java:87)
	at com.minelittlepony.client.render.entity.feature.GearFeature.render(GearFeature.java:80)
	at com.minelittlepony.client.render.entity.feature.GearFeature.method_4199(GearFeature.java:26)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.method_4215(PlayerPonyRenderer.java:77)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.method_3936(PlayerPonyRenderer.java:28)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1569)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
Mixins in Stacktrace:
	net.minecraft.class_922:
		traben.entity_texture_features.mixin.entity.renderer.MixinLivingEntityRenderer (#entity_texture_features:entity_texture_features-common.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.LivingEntityRendererAccessor (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.render.entity.MixinLivingEntityRenderer (#sodium-extra:sodium-extra.mixins.json)
		com.minelittlepony.unicopia.mixin.client.MixinLivingEntityRenderer (#unicopia:unicopia.mixin.json)
		dev.isxander.debugify.client.mixins.basic.mc197260.LivingEntityRendererMixin (#debugify:debugify.client.mixins.json)
		com.minelittlepony.bigpony.mixin.client.MixinLivingEntityRenderer (#bigpony:bigpony.mixin.json)
	net.minecraft.class_1007:
		traben.entity_texture_features.mixin.entity.renderer.MixinPlayerEntityRenderer (#entity_texture_features:entity_texture_features-common.mixins.json)
		eu.midnightdust.core.mixin.MixinPlayerEntityRenderer (#midnightlib:midnightlib.mixins.json)
		org.quiltmc.qsl.item.extension.mixin.crossbow.client.PlayerEntityRendererMixin (#quilt_item_extension:quilt_item_extension.mixins.json)
		dev.emi.trinkets.mixin.PlayerEntityRendererMixin (#trinkets:trinkets.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc227169.PlayerRendererMixin (#debugify:debugify.client.mixins.json)
		dev.isxander.debugify.client.mixins.basic.mc111516.PlayerRendererMixin (#debugify:debugify.client.mixins.json)
		com.minelittlepony.bigpony.mixin.client.MixinPlayerEntityRenderer (#bigpony:bigpony.mixin.json)
		com.minelittlepony.unicopia.mixin.client.MixinPlayerEntityRenderer (#unicopia:unicopia.mixin.json)
	net.minecraft.class_898:
		org.quiltmc.qsl.entity.multipart.mixin.client.EntityRenderDispatcherMixin (#quilt_entity_multipart:quilt_entity_multipart.mixins.json)
		com.minelittlepony.bigpony.mixin.client.MixinEntityRenderDispatcher (#bigpony:bigpony.mixin.json)
		com.minelittlepony.mson.impl.mixin.MixinEntityRenderDispatcher (#mson:mson.mixin.json)
		net.coderbot.iris.mixin.MixinEntityRenderDispatcher (#iris:mixins.iris.json)
		com.minelittlepony.client.mixin.MixinEntityRenderDispatcher (#minelp:minelp.mixin.json)
		com.minelittlepony.unicopia.mixin.client.MixinEntityRenderDispatcher (#unicopia:unicopia.mixin.json)
		org.quiltmc.qsl.resource.loader.mixin.client.KeyedClientResourceReloaderMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinEntityRenderDispatcher (#sodium:sodium.mixins.json)
		net.coderbot.iris.compat.sodium.mixin.vertex_format.entity.MixinEntityRenderDispatcher (#iris:mixins.iris.compat.sodium.json)
		net.coderbot.iris.mixin.entity_render_context.MixinEntityRenderDispatcher (#iris:mixins.iris.json)
		com.minelittlepony.common.mixin.MixinEntityRenderDispatcher (#kirin:kirin.mixin.json)
	net.minecraft.class_761:
		carpet.mixins.LevelRenderer_scarpetRenderMixin (#carpet:carpet.mixins.json)
		net.coderbot.iris.mixin.fantastic.MixinLevelRenderer (#iris:mixins.iris.fantastic.json)
		me.flashyreese.mods.sodiumextra.mixin.particle.MixinWorldRenderer (#sodium-extra:sodium-extra.mixins.json)
		com.b1n_ry.yigd.mixin.WorldRendererMixin (#yigd:yigd.mixins.json)
		vazkii.patchouli.mixin.client.MixinLevelRenderer (#patchouli:patchouli_xplat.mixins.json)
		net.blay09.mods.balm.mixin.LevelRendererMixin (#balm-fabric:balm.mixins.json)
		carpet.mixins.LevelRenderer_fogOffMixin (#carpet:carpet.mixins.json)
		net.coderbot.iris.mixin.LevelRendererAccessor (#iris:mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.sky.MixinWorldRenderer (#sodium-extra:sodium-extra.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.clouds.MixinWorldRenderer (#sodium:sodium.mixins.json)
		net.coderbot.iris.mixin.fabulous.MixinDisableFabulousGraphics (#iris:mixins.iris.json)
		net.coderbot.iris.mixin.sky.MixinLevelRenderer_SunMoonToggle (#iris:mixins.iris.json)
		net.coderbot.iris.mixin.shadows.MixinLevelRenderer (#iris:mixins.iris.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer (#iris:iris-batched-entity-rendering.mixins.json)
		com.minelittlepony.client.mixin.MixinWorldRenderer (#minelp:minelp.mixin.json)
		net.coderbot.iris.compat.sodium.mixin.sky.MixinLevelRenderer (#iris:mixins.iris.compat.sodium.json)
		org.quiltmc.qsl.resource.loader.mixin.client.KeyedClientResourceReloaderMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer_EntityListSorting (#iris:iris-batched-entity-rendering.mixins.json)
		net.coderbot.iris.mixin.shadows.MixinPreventRebuildNearInShadowPass (#iris:mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.sun_moon.MixinWorldRenderer (#sodium-extra:sodium-extra.mixins.json)
		shetiphian.core.mixins.SPC_WorldRenderer (#shetiphiancore:shetiphiancore.mixins.json)
		io.github.amerebagatelle.fabricskyboxes.mixin.skybox.WorldRendererAccess (#fabricskyboxes:fabricskyboxes.mixins.json)
		carpet.mixins.LevelRenderer_pausedShakeMixin (#carpet:carpet.mixins.json)
		com.minelittlepony.unicopia.mixin.client.MixinWorldRenderer (#unicopia:unicopia.mixin.json)
		carpet.mixins.LevelRenderer_creativeNoClipMixin (#carpet:carpet.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (#quilted_fabric_resource_loader_v0:quilted_fabric_resource_loader_v0.client.mixins.json)
		net.coderbot.iris.mixin.vertices.immediate.MixinLevelRenderer (#iris:mixins.iris.vertexformat.json)
		me.jellysquid.mods.sodium.mixin.features.options.MixinWorldRenderer (#sodium:sodium.mixins.json)
		dev.tr7zw.entityculling.mixin.WorldRendererMixin (#entityculling:entityculling.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.CommonWorldRendererMixin (#lambdynlights:lambdynlights.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinWorldRenderer (#sodium:sodium.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinWorldRenderer (#sodium:sodium.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.stars.MixinWorldRenderer (#sodium-extra:sodium-extra.mixins.json)
		io.github.amerebagatelle.fabricskyboxes.mixin.skybox.SkyboxRenderMixin (#fabricskyboxes:fabricskyboxes.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		net.coderbot.iris.mixin.MixinLevelRenderer (#iris:mixins.iris.json)
	net.minecraft.class_757:
		xaero.common.mixin.MixinGameRenderer (#xaerominimap:xaerominimap.mixins.json)
		com.jamieswhiteshirt.reachentityattributes.mixin.client.GameRendererMixin (#reach-entity-attributes:mixins.reach-entity-attributes.json)
		net.fabricmc.fabric.mixin.client.rendering.shader.GameRendererMixin (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		net.coderbot.iris.mixin.MixinTweakFarPlane (#iris:mixins.iris.json)
		com.minelittlepony.unicopia.mixin.client.MixinGameRenderer (#unicopia:unicopia.mixin.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (#iris:mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (#sodium-extra:sodium-extra.mixins.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (#iris:mixins.iris.json)
		vazkii.patchouli.mixin.client.MixinGameRenderer (#patchouli:patchouli_fabric.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.GameRendererMixin (#quilt_screen:quilt_screen.mixins.json)
		dev.architectury.mixin.fabric.client.MixinGameRenderer (#architectury:architectury.mixins.json)
		xaero.map.mixin.MixinGameRenderer (#xaeroworldmap:xaeroworldmap.mixins.json)
		mirsario.cameraoverhaul.fabric.mixins.modern.GameRendererMixin (#cameraoverhaul:cameraoverhaul.mixins.json)
		com.minelittlepony.client.mixin.MixinGameRenderer (#minelp:minelp.mixin.json)
		com.minelittlepony.bigpony.mixin.client.MixinGameRenderer (#bigpony:bigpony.mixin.json)
		dynamicfps.mixin.GameRendererMixin (#dynamicfps:dynamicfps.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer (#iris:mixins.iris.json)
		dev.isxander.zoomify.mixins.zoom.secondary.GameRendererMixin (#zoomify:zoomify.mixins.json)
		net.coderbot.iris.mixin.GameRendererAccessor (#iris:mixins.iris.json)
		org.quiltmc.qsl.resource.loader.mixin.client.KeyedClientResourceReloaderMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		reborncore.client.mixin.MixinGameRenderer (#reborncore:reborncore.client.mixins.json)
		dev.isxander.zoomify.mixins.zoom.GameRendererMixin (#zoomify:zoomify.mixins.json)
		org.anti_ad.mc.ipnext.mixin.MixinGameRenderer (#inventoryprofilesnext:mixins.ipnext.json)
		dev.isxander.debugify.client.mixins.basic.mc217716.GameRendererMixin (#debugify:debugify.client.mixins.json)
```

**Comment by coppercore** [comment]
Further testing confirmed it's Unicopia, as the crash doesn't happen without Unicopia enabled.

**Comment by Sollace** [comment]
Try with this version. The crashing should be fixed.

https://github.com/MineLittlePony/MineLittlePony/releases/tag/4.8.7%2Blts.1.19.3
