### ISSUE TITLE
Crash when shooting Flame spell to the ground frequently

### ISSUE THREAD

**Issue by FuTou2333** [Sollace/Unicopia#129]
When shooting Flame spell to the ground frequently for a while, the game will crash.
This problem can be repeated.
After the crash, sometimes just after entering the previous save, the game will crash.
```
---- Minecraft Crash Report ----
// My bad.

Time: 2023-06-29 10:36:09
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.google.common.collect.Iterators$1.next(Iterators.java:146)
	at net.minecraft.class_5572.method_31765(class_5572.java:33)
	at net.minecraft.class_5573.method_39465(class_5573.java:122)
	at net.minecraft.class_5573.method_31777(class_5573.java:65)
	at net.minecraft.class_5573.method_31783(class_5573.java:122)
	at net.minecraft.class_5578.method_31807(class_5578.java:43)
	at net.minecraft.class_1937.method_8333(class_1937.java:658)
	at com.minelittlepony.unicopia.util.VecHelper.findInRange(VecHelper.java:33)
	at com.minelittlepony.unicopia.ability.magic.Caster.findAllEntitiesInRange(Caster.java:97)
	at com.minelittlepony.unicopia.ability.magic.spell.effect.FireSpell.applyEntities(FireSpell.java:125)
	at com.minelittlepony.unicopia.ability.magic.spell.effect.FireSpell.tick(FireSpell.java:73)
	at com.minelittlepony.unicopia.projectile.MagicProjectileEntity.lambda$tick$1(MagicProjectileEntity.java:183)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at com.minelittlepony.unicopia.projectile.MagicProjectileEntity.method_5773(MagicProjectileEntity.java:183)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at com.google.common.collect.Iterators$1.next(Iterators.java:146)
	at net.minecraft.class_5572.method_31765(class_5572.java:33)
	at net.minecraft.class_5573.method_39465(class_5573.java:122)
	at net.minecraft.class_5573.method_31777(class_5573.java:65)
	at net.minecraft.class_5573.method_31783(class_5573.java:122)
	at net.minecraft.class_5578.method_31807(class_5578.java:43)
	at net.minecraft.class_1937.method_8333(class_1937.java:658)
	at com.minelittlepony.unicopia.util.VecHelper.findInRange(VecHelper.java:33)
	at com.minelittlepony.unicopia.ability.magic.Caster.findAllEntitiesInRange(Caster.java:97)
	at com.minelittlepony.unicopia.ability.magic.spell.effect.FireSpell.applyEntities(FireSpell.java:125)
	at com.minelittlepony.unicopia.ability.magic.spell.effect.FireSpell.tick(FireSpell.java:73)
	at com.minelittlepony.unicopia.projectile.MagicProjectileEntity.lambda$tick$1(MagicProjectileEntity.java:183)
	at java.base/java.util.Optional.filter(Optional.java:218)
	at com.minelittlepony.unicopia.projectile.MagicProjectileEntity.method_5773(MagicProjectileEntity.java:183)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: unicopia:magic_beam (com.minelittlepony.unicopia.projectile.MagicProjectileEntity)
	Entity ID: 1547
	Entity Name: entity.unicopia.magic_beam
	Entity's Exact location: -756.71, 29.62, 429.66
	Entity's Block location: World: (-757,29,429), Section: (at 11,13,13 in -48,1,26; chunk contains blocks -768,-64,416 to -753,319,431), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Entity's Momentum: 0.00, -1.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['FuTou2333'/31, l='ServerLevel[新的世界]', x=-756.72, y=69.18, z=429.55]]
	Chunk stats: 4893
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,66,16), Section: (at 0,2,0 in -3,4,1; chunk contains blocks -48,-64,16 to -33,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 304453 game time, 1000 day time
	Level name: 新的世界
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1315323232 bytes (1254 MiB) / 2587885568 bytes (2468 MiB) up to 3865051136 bytes (3686 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16093.23
	Virtual memory used (MB): 7956.40
	Swap memory total (MB): 8046.62
	Swap memory used (MB): 356.61
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx3686m
	Fabric Mods: 
		fabric-api: Fabric API 0.83.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		minelp: Mine Little Pony 4.9.0
			kirin: Kirin UI 1.15.0
			mson: Mson 1.8.1
		modmenu: Mod Menu 7.1.0
		replaymod: Replay Mod 1.20.1-2.6.13
		sodium: Sodium 0.4.10+build.27
		unicopia: Unicopia 1.1.1+1.20
			fabwork: Fabwork 1.2.0
			reach-entity-attributes: Reach Entity Attributes 2.3.3
			romanizer: Romanizer 1.0.2
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.0-beta.1
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.5
		xaeroworldmap: Xaero's World Map 1.30.6
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Server Running: true
	Player Count: 1 / 8; [class_3222['FuTou2333'/31, l='ServerLevel[新的世界]', x=-756.72, y=69.18, z=429.55]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.20.1
```

**Comment by FuTou2333** [comment]
It seems that only shooting straight down will cause the game to crash

**Comment by FuTou2333** [comment]
No, horizontal shooting can also crash the game
