### ISSUE TITLE
Minecraft Server Unicopia-Baubles support failed to load.

### ISSUE THREAD

**Issue by LunarstarFurry** [Sollace/Unicopia#15]
[16:59:16] [Server thread/ERROR]: Unicopia-Baubles support failed to load.                                                                                                                                               java.lang.ClassNotFoundException: com.minelittlepony.unicopia.extern.BaubleAlicornAmulet                                                                                                                                         at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]                                                                                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]                                                                                                                                                  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]                                                                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]                                                                                                                                                  at com.minelittlepony.unicopia.extern.Baubles.alicornAmulet(Baubles.java:44) [Baubles.class:?]                                                                                                                           at com.minelittlepony.unicopia.init.UItems.<clinit>(UItems.java:155) [UItems.class:?]                                                                                                                                    at com.minelittlepony.unicopia.init.Hooks.registerItems(Hooks.java:19) [Hooks.class:?]                                                                                                                                   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_82_Hooks_registerItems_Register.invoke(.dynamic) [?:Personal-4685e5b3]                                                                                     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:Personal-4685e5b3]                                                                                  at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:Personal-4685e5b3]                                                                                                  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) [EventBus.class:Personal-4685e5b3]                                                                                                        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:818) [GameData.class:Personal-4685e5b3]                                                                                                       at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628) [Loader.class:Personal-4685e5b3]                                                                                                              at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:Personal-4685e5b3]                                                                                at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:334) [FMLCommonHandler.class:Personal-4685e5b3]                                                                                    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) [nz.class:?]                                                                                                                    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:597) [MinecraftServer.class:?]                                                                                                                          at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Sollace** [comment]
1.15 no longer uses baubles
