### ISSUE TITLE
1.3.6 Crash on Launch

### ISSUE THREAD

**Issue by Hz6826** [Sollace/Unicopia#341]
Minecraft failed to start, presenting this error.

crash-2024-05-03_09.05.44-client.txt
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-05-03 09:05:44
Description: Rendering overlay

java.lang.IncompatibleClassChangeError: class com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget overrides final method net.minecraft.client.gui.widget.ClickableWidget.render(Lnet/minecraft/client/gui/DrawContext;IIF)V
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterTitleScreenInit(ModMenuEventHandler.java:86)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterScreenInit(ModMenuEventHandler.java:47)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.client.gui.screen.Screen.afterInit(Screen.java:1309)
	at net.minecraft.client.gui.screen.Screen.handler$zco000$fabric-screen-api-v1$afterInitScreen(Screen.java:1262)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:306)
	at net.minecraft.client.gui.screen.SplashOverlay.render(SplashOverlay.java:156)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:920)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1327)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterTitleScreenInit(ModMenuEventHandler.java:86)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterScreenInit(ModMenuEventHandler.java:47)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.client.gui.screen.Screen.afterInit(Screen.java:1309)
	at net.minecraft.client.gui.screen.Screen.handler$zco000$fabric-screen-api-v1$afterInitScreen(Screen.java:1262)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:306)
	at net.minecraft.client.gui.screen.SplashOverlay.render(SplashOverlay.java:156)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screen.SplashOverlay
Stacktrace:
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:920)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1327)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Uptime --
Details:
	JVM uptime: 36.003s
	Wall uptime: 24.093s
	High-res time: 7.579s
	Client ticks: 108 ticks / 5.400s
Stacktrace:
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2564)
	at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:995)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
	Recovery: Yes
	Recovery reason: java.lang.IncompatibleClassChangeError: class com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget overrides final method net.minecraft.client.gui.widget.ClickableWidget.render(Lnet/minecraft/client/gui/DrawContext;IIF)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterTitleScreenInit(ModMenuEventHandler.java:86)
	at com.terraformersmc.modmenu.event.ModMenuEventHandler.afterScreenInit(ModMenuEventHandler.java:47)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101)
	at net.minecraft.client.gui.screen.Screen.afterInit(Screen.java:1309)
	at net.minecraft.client.gui.screen.Screen.handler$zco000$fabric-screen-api-v1$afterInitScreen(Screen.java:1262)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:306)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient.java:1187)
	at net.minecraft.client.MinecraftClient.method_53528(MinecraftClient.java:746)
	at net.minecraft.client.MinecraftClient.collectLoadTimes(MinecraftClient.java:731)
	at net.minecraft.client.MinecraftClient.onFinishedLoading(MinecraftClient.java:720)
	at net.minecraft.client.MinecraftClient.method_29338(MinecraftClient.java:710)
	at net.minecraft.util.Util.ifPresentOrElse(Util.java:517)
	at net.minecraft.client.MinecraftClient.method_53522(MinecraftClient.java:705)
	at net.minecraft.client.gui.screen.SplashOverlay.render(SplashOverlay.java:149)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:920)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1327)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 474465792 bytes (452 MiB) / 1822425088 bytes (1738 MiB) up to 4246732800 bytes (4050 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Todesk Virtual Display Adapter
	Graphics card #0 vendor: Hainan YouQu Info Tech
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=16.44.2.509
	Graphics card #1 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x21c4
	Graphics card #1 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20238.84
	Virtual memory used (MB): 16679.65
	Swap memory total (MB): 4044.80
	Swap memory used (MB): 142.73
	JVM Flags: 0 total; 
	Fabric Mods: 
		com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.2
		fabric-api: Fabric API 0.91.2+1.20.4
		fabric-api-base: Fabric API Base 0.4.35+78d798af4f
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
		fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
		fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
		fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
		fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
		fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
		fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.27+78d798af4f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.14+78d798af4f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.19+78d798af4f
		fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
		fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
		fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
		fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
		fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.7+78d798af4f
		fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
		fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
		fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.1
		fabwork: Fabwork 1.3.0+1.20.2
		hdskins: HD Skins 6.11.0+1.20.2
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.17.1+1.20.4
		minecraft: Minecraft 1.20.4
		minelp: Mine Little Pony 4.11.6+1.20.2
		modmenu: Mod Menu 8.0.0
		mson: Mson 1.9.3+1.20.2
		noindium: No Indium? 1.1.0+1.20
		reach-entity-attributes: Reach Entity Attributes 2.4.2
		terraform-wood-api-v1: Terraform Wood API (v1) 8.0.0-beta.1
		unicopia: Unicopia 1.3.6+1.20.4
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: 
	Current Language: zh_cn
	Locale: zh_CN
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F
```

**Comment by MimzyFang** [comment]
May I ask where you got that version of modmenu from the only one I could find for 1.20.4 was version 9 
https://modrinth.com/mod/modmenu/version/9.0.0

**Comment by Sollace** [comment]
This is caused by mod menu.

**Comment by Hz6826** [comment]
I replaced the wrong Mod Menu, but it crashed again. I guess Unicopia may not be compatible with Sodium.

Specifically, it's like:
ONLY Sodium    Success
ONLY Unicopia    Success(duh)
1.3.0 Unicopia + Sodium    Success
1.3.1~1.3.6 Unicopia + Sodium    Failed (java.lang.NoSuchMethodError: 'void net.minecraft.class_4286.<init>(int, int, int, int, net.minecraft.class_2561, boolean)')

## Log
[unicopia+sodium.log](https://github.com/Sollace/Unicopia/files/15208053/unicopia%2Bsodium.log)

**Comment by Hz6826** [comment]
Same as Issue #156 .
