### ISSUE TITLE
Game Crashes Because Of Wearing Alicorn Amulet

### ISSUE THREAD

**Issue by OakPlatinum** [Sollace/Unicopia#400]
I used the latest version of Unicopia (1.3.8+1.20.4), and after I wore the alicorn amulet, the game was just keeping crashing whenever I tried to load.
Older versions worked fine with the amulet.

BTW, THIS IS THE 400TH ISSUE. YAY!

**CRASH REPORT**
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-10 14:25:46
Description: Ticking player

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at com.minelittlepony.unicopia.entity.AttributeContainer.updateAttributeModifier(AttributeContainer.java:35)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.lambda$updateAttributes$1(AlicornAmuletItem.java:180)
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap$MapEntrySet.forEach(Object2FloatOpenHashMap.java:1066)
	at it.unimi.dsi.fastutil.objects.ObjectCollections$UnmodifiableCollection.forEach(ObjectCollections.java:387)
	at it.unimi.dsi.fastutil.objects.ObjectSets$UnmodifiableSet.forEach(ObjectSets.java:221)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.updateAttributes(AlicornAmuletItem.java:179)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.method_7888(AlicornAmuletItem.java:300)
	at net.minecraft.class_1799.method_7917(class_1799.java:518)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:579)
	at net.minecraft.class_1309.method_5773(class_1309.java:2446)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:519)
	at net.minecraft.class_3244.method_18784(class_3244.java:257)
	at net.minecraft.class_2535.method_10754(class_2535.java:379)
	at net.minecraft.class_3242.method_14357(class_3242.java:176)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1324.method_6197(class_1324.java:73)
	at net.minecraft.class_1324.method_26835(class_1324.java:81)
	at com.minelittlepony.unicopia.entity.AttributeContainer.updateAttributeModifier(AttributeContainer.java:35)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.lambda$updateAttributes$1(AlicornAmuletItem.java:180)
	at it.unimi.dsi.fastutil.objects.Object2FloatOpenHashMap$MapEntrySet.forEach(Object2FloatOpenHashMap.java:1066)
	at it.unimi.dsi.fastutil.objects.ObjectCollections$UnmodifiableCollection.forEach(ObjectCollections.java:387)
	at it.unimi.dsi.fastutil.objects.ObjectSets$UnmodifiableSet.forEach(ObjectSets.java:221)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.updateAttributes(AlicornAmuletItem.java:179)
	at com.minelittlepony.unicopia.item.AlicornAmuletItem.method_7888(AlicornAmuletItem.java:300)
	at net.minecraft.class_1799.method_7917(class_1799.java:518)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:579)
	at net.minecraft.class_1309.method_5773(class_1309.java:2446)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 1374
	Entity Name: NoodAifie
	Entity's Exact location: 7.09, 67.00, 11.95
	Entity's Block location: World: (7,67,11), Section: (at 7,3,11 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:519)
	at net.minecraft.class_3244.method_18784(class_3244.java:257)
	at net.minecraft.class_2535.method_10754(class_2535.java:379)
	at net.minecraft.class_3242.method_14357(class_3242.java:176)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1083570904 bytes (1033 MiB) / 6228541440 bytes (5940 MiB) up to 6228541440 bytes (5940 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Virtual Display Device
	Graphics card #0 vendor: Huawei
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.0.9
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1934
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 21996.24
	Virtual memory used (MB): 19075.10
	Swap memory total (MB): 5888.00
	Swap memory used (MB): 77.32
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn890m -Xmx5939m
	Fabric Mods: 
		allmusic_client: AllMusic Client 3.0.0
		appleskin: AppleSkin 2.5.1+mc1.20.3
		architectury: Architectury 11.1.17
		auudio: Auudio 1.0.3
		balm-fabric: Balm 9.0.8
		bclib: BCLib 3.30.1
			wunderlib: WunderLib 1.30.0
		beautify: Beautify 1.2.0+1.20.4
		betterdeserttemples: YUNG's Better Desert Temples 1.20.4-Fabric-3.4.4
		betterdungeons: YUNG's Better Dungeons 1.20.4-Fabric-4.4.4
		betterendisland: YUNG's Better End Island 1.20.4-Fabric-2.4.3
		betterf3: BetterF3 9.0.2
		betterfortresses: YUNG's Better Nether Fortresses 1.20.4-Fabric-2.4.4
		betterjungletemples: YUNG's Better Jungle Temples 1.20.4-Fabric-2.4.4
		bettermineshafts: YUNG's Better Mineshafts 1.20.4-Fabric-4.4.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20.4-Fabric-3.4.3
		betterstrongholds: YUNG's Better Strongholds 1.20.4-Fabric-4.4.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20.4-Fabric-3.4.3
		bigpony: Big Pony 1.11.2+1.20.4
		bobby: Bobby 5.1.0+mc1.20.4
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.67
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.67
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.67
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.67
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.67
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.67
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.67
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.67
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.67
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.67
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.67
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.67
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.67
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.67
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.67
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.67
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.67
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.67
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.67
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.67
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.67
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.4.0
			cardinal-components-base: Cardinal Components API (base) 5.4.0
			cardinal-components-block: Cardinal Components API (blocks) 5.4.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.4.0
			cardinal-components-entity: Cardinal Components API (entities) 5.4.0
			cardinal-components-item: Cardinal Components API (items) 5.4.0
			cardinal-components-level: Cardinal Components API (world saves) 5.4.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.4.0
			cardinal-components-world: Cardinal Components API (worlds) 5.4.0
		chatimage: ChatImage 1.2.4+1.20.4+fabric
			actionlib: ActionLib 1.0.2-fabric
			io_github_kituin_chatimagecode: ChatImageCode 0.9.7
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 15.0.0.2
		controlling: Controlling 15.0.5
		crafttweaker: CraftTweaker 17.0.19
			org_reflections_reflections: reflections 0.10.2
		diamondchestshop: Diamond Chest Shop 1.2.6+1.20
		diamondeconomy: Diamond Economy 1.5.6
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0.3
			placeholder-api: Placeholder API 2.2.0+1.20.2
		distanthorizons: Distant Horizons 2.1.2-a
		emi: EMI 1.1.6+1.20.4+fabric
		emitrades: EMI Trades 1.3.0+mc1.20.4
			org_quiltmc_parsers_json: json 0.2.1
		endrem: End Remastered 5.2.4
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.4
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20.4
				kmodlib-overlay: KModLib Overlay 0.2.13+1.20.3
				libnetworkstack: Lib Network Stack 0.11.0-pre.1
			noindium: No Indium? 1.1.0+1.20.4
			yet_another_config_lib_v3: YetAnotherConfigLib 3.3.1+1.20.4
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fancymenu: FancyMenu 3.2.3
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fmsia: FancyMenu | System Interactions Addon 1.0.1
		framework: Framework 0.7.6
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		ftbchunks: FTB Chunks 2004.1.2
		ftbessentials: FTB Essentials 2004.1.2
		ftblibrary: FTB Library 2004.2.2
		ftbranks: FTB Ranks 2004.2.0
		ftbteams: FTB Teams 2004.1.2
		hdskins: HD Skins 6.12.2+1.20.4
		i18nupdatemod: I18nUpdateMod 3.5.5
		indium: Indium 1.0.30+mc1.20.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		iris: Iris 1.7.0+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 13.3.1
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 17.3.0.52
		kirin: Kirin UI 1.17.1+1.20.4
		konkrete: Konkrete 1.9.2
		lambdynlights: LambDynamicLights 2.3.4+1.20.4
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.3+1.20.2
		libipn: libIPN 4.0.2
		lithium: Lithium 0.12.1
		melody: Melody 1.0.3
		minecraft: Minecraft 1.20.4
		minelp: Mine Little Pony 4.11.7+1.20.4
			mson: Mson 1.9.3+1.20.2
		modmenu: Mod Menu 9.2.0-beta.2
		mousetweaks: Mouse Tweaks 2.26
		mtr: Minecraft Transit Railway 4.0.0-beta-8
		nbt_ac: NBT Autocomplete 1.2.1
		nochatreports: No Chat Reports 1.20.4-v2.6.0
		patchouli: Patchouli 1.20.4-85-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		searchables: Searchables 1.0.6
		sodium: Sodium 0.5.8+mc1.20.4
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		travelersbackpack: Traveler's Backpack fabric-1.20.4-9.4.6
			reach-entity-attributes: Reach Entity Attributes 2.5.0
		travelerstitles: Traveler's Titles 1.20.4-Fabric-4.4.1
		trinkets: Trinkets 3.8.1
		unicopia: Unicopia 1.3.8+1.20.4
			fabwork: Fabwork 1.3.0+1.20.2
			romanizer: Romanizer 1.0.2
			terraform-wood-api-v1: Terraform Wood API (v1) 8.0.0-beta.1
		veinmining: Vein Mining 3.1.1+1.20.4
			spectrelib: SpectreLib 0.15.2+1.20.4
		viafabricplus: ViaFabricPlus 3.1.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0
			com_viaversion_viaversion-common: viaversion-common 4.10.0
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_lenni0451_reflect: Reflect 1.3.2
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11
			net_raphimc_viabedrock: ViaBedrock 0.0.6-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22
			net_raphimc_vialoader: ViaLoader 2.2.13
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		videoplayer: Video Player 2.6.1
		voicechat: Simple Voice Chat 1.20.4-2.5.15
		watermedia: watermedia 2.0.64
		waystones: Waystones 16.0.5
		worldedit: WorldEdit 7.3.0+6678-55745ad
		worldeditcui: WorldEditCUI 1.20.3+01
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroplus: XaeroPlus 2.9
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.8
			net_lenni0451_lambdaevents: LambdaEvents 2.4.2
		xaeroworldmap: Xaero's World Map 1.38.4
		yungsapi: YUNG's API 1.20.4-Fabric-4.4.3
		yungsbridges: YUNG's Bridges 1.20.4-Fabric-4.4.2
		yungsextras: YUNG's Extras 1.20.4-Fabric-4.4.2
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['NoodAifie'/1374, l='ServerLevel[新的世界]', x=7.09, y=67.00, z=11.95]]
	Data Packs: vanilla, fabric, balm-fabric (incompatible), bclib, beautify, betterdeserttemples, betterdungeons, betterendisland, betterfortresses, betterjungletemples, bettermineshafts, betteroceanmonuments, betterstrongholds, betterwitchhuts, crafttweaker (incompatible), endrem, extended_drawers, fabric-convention-tags-v1, ftbchunks, ftbessentials (incompatible), mtr, patchouli (incompatible), travelersbackpack, travelerstitles, trinkets, unicopia, veinmining (incompatible), videoplayer, waystones (incompatible), yungsbridges, yungsextras
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: ppppppppppppppp
```

**Comment by ColdStoneSys** [comment]
Ive noticed this happens when the amulet's corruption is trying to spread near a large group of mobs (farms).
