### ISSUE TITLE
Server Crash when Earth ponie tries to kick (Beta 23, Fabric 0.14.9, API 0.61.0, MC 1.19.2)

### ISSUE THREAD

**Issue by Alex-1302** [Sollace/Unicopia#63]
Server crashes when an earth pony tries to kick blocks.

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at com.minelittlepony.unicopia.ability.EarthPonyKickAbility.getDefaultKickLocation(EarthPonyKickAbility.java:115)
	at com.minelittlepony.unicopia.ability.EarthPonyKickAbility.onQuickAction(EarthPonyKickAbility.java:74)
	at com.minelittlepony.unicopia.network.MsgPlayerAbility.handle(MsgPlayerAbility.java:53)
	at com.minelittlepony.unicopia.network.MsgPlayerAbility.handle(MsgPlayerAbility.java:20)
	at com.minelittlepony.unicopia.util.network.SimpleNetworking.lambda$clientToServer$0(SimpleNetworking.java:47)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 18 more

**Comment by Sollace** [comment]
I need the full crashlog please.

Also if you have mine little pony installed on the server, please remove it.

**Comment by FollowSlipstream** [comment]
Hello!
I've attached a full crash log. No MineLP is installed but I guess the log contains that kind of info anyway. So far no other actions seem to have crashed the server.
[crash-2022-09-23_15.50.30-server.txt](https://github.com/Sollace/Unicopia/files/9634268/crash-2022-09-23_15.50.30-server.txt)
